appDomain: change-me
partOf: trustify
replicas: 1

image:
  fullName: registry.redhat.io/rhtpa/rhtpa-rhel10@sha256:928477e2a2310b523f942878801d02cea419aadd0ad94df7ee94ee5c76ffb848
  pullPolicy: IfNotPresent

rust: {}

proxy: {}

readOnly: false

ingress:
  enabled: true

tls: {}

storage: {}

database: {}

openshift:
  useServiceCa: true

oidc:
  uiScope: ""
  loadUser: true
  clients:
    frontend: {}
    cli:
      clientSecret:

infrastructure:
  port: 9010

metrics:
  enabled: false

tracing:
  enabled: false

collector: {}

exploitIntelligence:
  enabled: false

modules:
  server:
    enabled: true
    ingress: {}
    image: {}
    infrastructure: {}
    tracing: {}
    metrics: {}
    rust: {}
    cacheTTL: "60sec"
    recommendPatterns: []
    resources:
      requests:
        cpu: 1
        memory: 8Gi

  importer:
    enabled: true
    image: {}
    infrastructure: {}
    tracing: {}
    metrics: {}
    rust: {}
    resources:
      requests:
        cpu: 1
        memory: 8Gi
    concurrency: 1
    # readOnly: false
    workingDirectory:
      size: 32Gi

  createDatabase:
    enabled: false
    image:
      name: postgres
      registry: docker.io/library
      version: "17.2"

  migrateDatabase:
    enabled: false
    image: {}
    # dataMigrationSkip:
    #   - m0002000_add_sbom_properties
    # dataMigrationSkipAll: false

  createImporters:
    enabled: false
    image:
      name: postgres
      registry: docker.io/library
      version: "17.2"
    importers: {}
